esphome:
  name: and_a7670

esp32:
  board: wemos_d1_mini32
  


packages:
  modem_package:
    url: https://github.com/oarcher/piotech
    files:
      # include only one model!
      #- packages/lilygo_tsim7600.yaml # https://lilygo.cc/en-us/products/t-sim7600
      #- packages/waveshare_ESP32-S3-A7670E-4G.yaml # https://docs.waveshare.com/ESP32-S3-A7670E-4G
      - packages/and_A7670.yaml
  
      - packages/modem_common.yaml
      - packages/modem_external.yaml  # for automatic external components (while PR not merged)
      - packages/modem_wifi_ap.yaml   # for testing wifi AP
    refresh: 10s  # optional
  


modem:
  id: atmodem
  # FIXME (should work on HW uart)
  # rx_pin: GPIO03
  # tx_pin: GPIO01 # connected to RX on the modem side
  rx_pin: GPIO21 # connected to T on the modem side
  tx_pin: GPIO22 # connected to R on the modem side
  model: SIM7670
  apn: orange
  pin_code: "0000"



