#!/bin/bash

set -e
# set -x

mkdir -p config
#script/setup

cpp_json=.vscode/c_cpp_properties.json
if [ ! -f $cpp_json ]; then
    echo "Initializing PlatformIO..."
    pio init --ide vscode --silent
    sed -i "/\\/workspaces\/piotech\/include/d" $cpp_json
else
    echo "Cpp environment already configured. To reconfigure it you can run one the following commands:"
    echo "  pio init --ide vscode"
fi

if [! -d esphome_official ]; then
    echo 'esphome sources are not installed. run ./build.sh outside the container and retry'
else
    pip3 install --break-system-packages --no-cache-dir --no-use-pep517 -e esphome_official
fi

