esp32:
  board: esp-wrover-kit
esphome:
  name: lilygo_tsim7600

modem:
  id: atmodem
  rx_pin: GPIO26
  tx_pin: GPIO27
  model: SIM7600
  # URC text sensor - publishes Unsolicited Result Codes from modem
  urc:
    name: "Modem URCs"
    filters:
      - lambda: |-
          // forward NMEA sentences to virtual uart, so GPS can read them
          if(x.find("$GPGGA") != std::string::npos || x.find("$GPRMC") != std::string::npos) {
            ESP_LOGI("NMEA", "got NMEA sentence: %s", x.c_str());
            id(atmodem)->write_array((const uint8_t*)x.c_str(), x.length());  // write to uart (for gps)
            id(gps_id)->update();
            return {}; // Filter out NMEA
          }
          return x;

  on_sync:
    - modem.send_at: AT+CGPS=1 # poweron GPS
    - modem.send_at: AT+CGPSINFOCFG=10,3 # nmea sentence every 10s GPGGA and GPRMC

# ton/toff value from https://simcom.ee/documents/SIM7600E/SIM7600%20Series%20Hardware%20Design_V1.03.pdf
# p 24-25
script:
  - id: modem_on
    mode: single
    then:
      - logger.log: modem POWERON begin...
      - switch.turn_on: modem_power
      - delay: 500ms
      - switch.turn_off: modem_power
      - delay: 12s
      - logger.log: modem POWERON done

  - id: modem_off
    mode: single
    then:
      - logger.log: modem POWEROFF begin...
      - switch.turn_on: modem_power
      - delay: 2700ms
      - switch.turn_off: modem_power
      - delay: 15s
      - logger.log: modem POWEROFF done

gps:
  uart_id: atmodem
  id: gps_id
  latitude:
    name: "Latitude"
  longitude:
    name: "Longitude"
  altitude:
    name: "Altitude"
  update_interval:  never

binary_sensor:
  - platform: gpio
    name: modem status
    id: modem_status
    pin: GPIO34

switch:
  - platform: gpio
    id: flight_mode
    name: flight mode
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO25
      inverted: True  # internaly, must be low to disable communiquation
  - platform: gpio
    id: modem_power
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO04
      inverted: True 
  

light:
  - platform: status_led
    name: "Switch status led"
    pin: GPIO12










