esp32:
  board: esp-wrover-kit
esphome:
  name: lilygo_tsim7600

modem:
  id: atmodem
  rx_pin: GPIO26
  tx_pin: GPIO27
  model: SIM7600
  power_pin:
    pin:
      number: GPIO04
      inverted: True # https://github.com/Xinyuan-LilyGO/LilyGO-T-SIM7000G/issues/251#issuecomment-1807142449

  # URC text sensor - publishes Unsolicited Result Codes from modem
  urc:
    name: "Modem URCs"
    filters:
      - lambda: |-
          // forward NMEA sentences to virtual uart, so GPS can read them
          if(x.find("$GPGGA") != std::string::npos || x.find("$GPRMC") != std::string::npos) {
            ESP_LOGI("NMEA", "got NMEA sentence: %s", x.c_str());
            id(atmodem)->write_array((const uint8_t*)x.c_str(), x.length());  // write to uart (for gps)
            id(gps_id)->update();
            return {}; // Filter out NMEA
          }
          return x;

  on_sync:
    - modem.send_at: AT+CGPS=1 # poweron GPS
    - modem.send_at: AT+CGPSINFOCFG=10,3 # nmea sentence every 10s GPGGA and GPRMC

gps:
  uart_id: atmodem
  id: gps_id
  latitude:
    name: "Latitude"
  longitude:
    name: "Longitude"
  altitude:
    name: "Altitude"
  update_interval:  never

binary_sensor:
  - platform: gpio
    name: modem status
    id: modem_status
    pin: GPIO34

switch:
  - platform: gpio
    id: flight_mode
    name: flight mode
    restore_mode: ALWAYS_OFF
    pin:
      number: GPIO25
      inverted: True  # internaly, must be low to disable communiquation

light:
  - platform: status_led
    name: "Switch status led"
    pin: GPIO12







