esp32:
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_ESP_TASK_WDT_TIMEOUT_S: "60"

sensor:
  - platform: modem_info
    rssi:
      name: rssi
    ber:
      name: ber

text_sensor:
  - platform: modem_info
    network_type:
      name: Network type
    signal_strength:
      name: Signal strength
      