# Set internal debug log


esphome: 
  on_boot: 
    - priority: 600
      then:
        - lambda: |-
            // esp_log_level_set("command_lib", ESP_LOG_VERBOSE);
            esp_log_level_set("DCE mode", ESP_LOG_VERBOSE);

logger:
  level: DEBUG

esp32:
  framework:
    type: esp-idf
    sdkconfig_options:
      # CONFIG_LOG_MAXIMUM_LEVEL_VERBOSE: "y"
      CONFIG_LOG_MAXIMUM_LEVEL_DEBUG: "y"



